##### Bag of Words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"texts" : ["He is going to play football", "I am very sick to play football", "How will you play football", "Is this right time to play cricket"], "Output" : [1, 1, 0, 0]})

In [3]:
df

texts  Output
0        He is going to play football       1
1     I am very sick to play football       1
2          How will you play football       0
3  Is this right time to play cricket       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['texts'])

In [7]:
#vocabulary
print(cv.vocabulary_)

{'he': 4, 'is': 6, 'going': 3, 'to': 12, 'play': 7, 'football': 2, 'am': 0, 'very': 13, 'sick': 9, 'how': 5, 'will': 14, 'you': 15, 'this': 10, 'right': 8, 'time': 11, 'cricket': 1}


In [8]:
bow.toarray()

array([[0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0]])

In [9]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 1 1 0 1 1 0 0 0 0 1 0 0 0]]
[[1 0 1 0 0 0 0 1 0 1 0 0 1 1 0 0]]
[[0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1]]


In [10]:
# new
cv.transform(['He will you play cricket instead of football']).toarray()

array([[0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1]])

In [11]:
x = bow.toarray()
y = df['Output']

In [12]:
x

array([[0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0]])

In [13]:
y

0    1
1    1
2    0
3    0
Name: Output, dtype: int64

##### N-grams

In [14]:
df = pd.DataFrame({"texts" : ["He is going to play football", "I am very sick to play football", "How will you play football", "Is this right time to play cricket"], "Output" : [1, 1, 0, 0]})

In [15]:
df

texts  Output
0        He is going to play football       1
1     I am very sick to play football       1
2          How will you play football       0
3  Is this right time to play cricket       0

In [16]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [17]:
bow = cv.fit_transform(df['texts'])

In [18]:
print(cv.vocabulary_)

{'he is': 2, 'is going': 4, 'going to': 1, 'to play': 12, 'play football': 7, 'am very': 0, 'very sick': 13, 'sick to': 9, 'how will': 3, 'will you': 14, 'you play': 15, 'is this': 5, 'this right': 10, 'right time': 8, 'time to': 11, 'play cricket': 6}


In [19]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0]]
[[1 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0]]
[[0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1]]


In [20]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [21]:
bow = cv.fit_transform(df['texts'])

In [22]:
print(cv.vocabulary_)

{'he is going': 2, 'is going to': 4, 'going to play': 1, 'to play football': 11, 'am very sick': 0, 'very sick to': 12, 'sick to play': 7, 'how will you': 3, 'will you play': 13, 'you play football': 14, 'is this right': 5, 'this right time': 8, 'right time to': 6, 'time to play': 9, 'to play cricket': 10}


In [23]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 0 1 0 0 0 0 0 0 1 0 0 0]]
[[1 0 0 0 0 0 0 1 0 0 0 1 1 0 0]]
[[0 0 0 1 0 0 0 0 0 0 0 0 0 1 1]]


##### TF-IDF (Term frequency- Inverse document frequency)

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [25]:
arr = tfid.fit_transform(df['texts']).toarray()

In [26]:
arr

array([[0.        , 0.        , 0.33143877, 0.51926288, 0.51926288,
        0.        , 0.40939282, 0.27097291, 0.        , 0.        ,
        0.        , 0.        , 0.33143877, 0.        , 0.        ,
        0.        ],
       [0.4946412 , 0.        , 0.31572307, 0.        , 0.        ,
        0.        , 0.        , 0.2581243 , 0.        , 0.4946412 ,
        0.        , 0.        , 0.31572307, 0.4946412 , 0.        ,
        0.        ],
       [0.        , 0.        , 0.33274238, 0.        , 0.        ,
        0.52130524, 0.        , 0.2720387 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.52130524,
        0.52130524],
       [0.        , 0.4343181 , 0.        , 0.        , 0.        ,
        0.        , 0.34242138, 0.2266452 , 0.4343181 , 0.        ,
        0.4343181 , 0.4343181 , 0.27721962, 0.        , 0.        ,
        0.        ]])

In [27]:
print(tfid.idf_)

[1.91629073 1.91629073 1.22314355 1.91629073 1.91629073 1.91629073
 1.51082562 1.         1.91629073 1.91629073 1.91629073 1.91629073
 1.22314355 1.91629073 1.91629073 1.91629073]
